services:
  frontend-landing:
    build: 
      context: frontends/landing
      dockerfile: Dockerfile
    expose:
      - 80

  backend-ai-images:
    build: 
      context: backends/ai_image_generator
      dockerfile: Dockerfile
    ipc: host
    shm_size: 8G
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    environment:
      S3_HOST: ${S3_HOST}
      S3_PORT: ${S3_PORT}
      S3_BUCKET: ${S3_BUCKET}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017/
      HF_HOME: "/root/.cache/huggingface"
    working_dir: /app
    volumes:
      - "/home/nontre/.cache/huggingface:/root/.cache/huggingface"
    depends_on:
      - minio
      - rabbitmq
      - mongo

  backend-images:
    build: 
      context: backends/image_provider
      dockerfile: Dockerfile
    expose:
      - 8080
    environment:
      MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017/
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8083:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017/
    depends_on:
      - mongo

  minio:
    image: minio/minio
    ports:
      - 9001:9001
    expose:
      - 9000
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASS}
    volumes:
      - ./cdn/minio/data:/data
    command: server /data --console-address ":9001"

  nginx:
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ./cdn/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend-landing
      - backend-images
      - minio
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "15672:15672"
    expose:
      - 5672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mongo_data:
  minio_data:
  rabbitmq_data:
