services:
  frontend-landing:
    image: frontend-landing
    build: 
      context: frontends/landing
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  backend-ai-images:
    image: backen-ai-images
    build: 
      context: backends/ai_image_generator
      dockerfile: Dockerfile
    runtime: rocm
    ipc: host
    shm_size: 8G
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    ports:
      - "8081:8080"
    environment:
      S3_HOST: ${S3_HOST}
      S3_PORT: ${S3_PORT}
      S3_BUCKET: ${S3_BUCKET}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017/
    depends_on:
      - minio
      - rabbitmq
      - mongo

  backend-images:
    image: backend-images
    build: 
      context: backends/image_provider
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017/
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8083:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017/
    depends_on:
      - mongo

  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ACCESS_KEY: ${S3_ACCESS_KEY}
      MINIO_SECRET_KEY: ${S3_SECRET_KEY}
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data

  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mongo_data:
  minio_data:
  rabbitmq_data:
